<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anggreani Gifanti">
<meta name="dcterms.date" content="2025-01-01">

<title>Pengaruh Gross Domestic Product (GDP) terhadap Volume Ekspor Rumput Laut Indonesia ke 10 Negara Tujuan Utama Tahun 2019-2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Gross Domestic Product (GDP) terhadap Volume Ekspor Rumput Laut Indonesia ke 10 Negara Tujuan Utama Tahun 2019-2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anggreani Gifanti </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia merupakan salah satu produsen rumput laut terbesar di dunia, dengan pasar ekspor yang tersebar di berbagai negara. Rumput laut tidak hanya menjadi komoditas unggulan, tetapi juga sumber devisa yang penting bagi negara. 10 Negara tujuan utama ekspor rumput laut di antaranya China, Viet Nam, Chile, Korea Selatan, Japan, Spain, Amerika Serikat, Filipina, Perancis, dan Hong Kong.</p>
<p>Penulis tertarik melihat ekspor rumput laut karena, rumput laut saat ini merupakan salah satu komoditas yang memiliki nilai ekonomi tinggi mengingat perannya yang sangat penting dalam berbagai produk yang berhubungan dengan kehidupan sehari-hari. Misalnya sebagai bahan makanan seperti agar-agar, sayuran, kue dan menghasilkan bahan algin, karaginan dan fulcelaran yang digunakan dalam industri farmasi, kosmetik, dan tekstil. Penelitian ini bertujuan untuk memahami bagaimana GDP negara tujuan dan harga rumput laut memengaruhi volume ekspor Indonesia ke 10 negara utama dalam periode 2019-2023.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini menggunakan data yang diambil dari World Development Indicators, World Bank dan Trademap.org. Penelitian ini terdapat 2 variabel yaitu GDP dari 10 negara tujuan utama ekspor rumput laut Indonesia (China, Viet Nam, Chile, Korea Selatan, Japan, Spain, Amerika Serikat, Filipina, Perancis, dan Hong Kong) dalam USD dan ekspor rumput laut dalam satuan ton. Data yang digunakan adalah data yang bersifat time series yaitu dalam kurun waktu 2019-2023. Ekspor rumput laut sendiri data yang digunakan adalah rumput laut dengan hs code 121221. Metode analisis yang digunakan adalah regresi linier sederhana (OLS).</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang diatas maka yang menjadi masalah pokok pada penelitian ini adalah: 1. Bagaimana hubungan antara GDP negara tujuan dan volume ekspor rumput laut Indonesia? 2. Apakah GDP negara tujuan secara signifikan memengaruhi volume ekspor rumput laut Indonesia?</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini bertujuan untuk: 1. Mengetahui hubungan antara GDP negara tujuan dengan volume ekspor rumput laut Indonesia. 2. Menganalisis pengaruh GDP terhadap volume ekspor rumput laut Indonesia ke 10 negara tujuan utama.<br>
3. Mengidentifikasi sejauh mana GDP memengaruhi ekspor ke masing-masing negara. 4. Memberikan rekomendasi strategis kepada pelaku industri dan pembuat kebijakan untuk meningkatkan daya saing ekspor rumput laut.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Rumput laut adalah salah satu tumbuhan laut yang tergolong dalam makroalga benthik yang banyak hidup melekat di dasar perairan (Atillah &amp; Gischa, 2023). Di banyak negara termasuk Indonesia, rumput laut saat ini merupakan salah satu komoditas yang memiliki nilai ekonomi tinggi mengingat perannya yang sangat penting dalam berbagai produk yang berhubungan dengan kehidupan sehari-hari. Misalnya sebagai bahan makanan seperti agar-agar, sayuran, kue dan menghasilkan bahan algin, karaginan dan fulcelaran yang digunakan dalam industri farmasi, kosmetik, dan tekstil. (Salim, 2015)</p>
<p>Menurut (Saputra, 2024), telah berbagai faktor yang mempengaruhi volume ekspor rumput laut Indonesia. Penelitian ini menunjukkan bahwa faktor-faktor seperti permintaan pasar, harga internasional, dan kebijakan pemerintah berperan signifikan dalam menentukan volume ekspor. Penelitian ini juga menekankan pentingnya diversifikasi pasar untuk meningkatkan daya saing ekspor rumput laut Indonesia di pasar global.</p>
<p>Literature berikutnya adalah buku yang disunting oleh Zamroni Salim, Ph.D dan Ernawati, Ph.D (2015) ini memberikan informasi komprehensif mengenai rumput laut sebagai komoditas ekspor. Dalam buku ini, dijelaskan bahwa rumput laut memiliki berbagai manfaat, baik untuk industri makanan, kosmetik, maupun farmasi. Selain itu, buku ini juga membahas potensi pasar rumput laut di luar negeri dan tantangan yang dihadapi oleh Indonesia dalam meningkatkan volume ekspor.</p>
<p>Menurut (Arthatiani et al., 2021) mengkaji dampak pandemi terhadap kinerja ekspor rumput laut. Penelitian ini menunjukkan bahwa meskipun terjadi penurunan permintaan global, sektor rumput laut tetap memiliki peluang untuk berkembang jika didukung oleh kebijakan yang tepat.</p>
<p>Menurut (Simanjuntak et al., n.d.) meneliti bagaimana faktor-faktor Produksi, Harga Internasional dan Nilai Tukar Rupiah mempengaruhi volume ekspor. Hasil penelitian menunjukkan bahwa produksi rumput laut dan nilai tukar memiliki pengaruh signifikan terhadap volume ekspor, sementara harga internasional tidak memberikan dampak yang konsisten.</p>
<p>Penelitian-penelitian tersebut memberikan dasar yang kuat untuk memahami dinamika ekspor rumput laut dan pentingnya strategi yang tepat untuk meningkatkan kinerja ekspor di masa depan.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian, data dibawah ini merupakan data nilai ekspor dalam satuan ton, GDP dalam satuan USD, serta data export dan gdp setelah transformasi log.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 31%">
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Tahun</th>
<th>Negara</th>
<th>Export</th>
<th>GDP</th>
<th>lexport</th>
<th>lgdp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2019</td>
<td>China</td>
<td>146710</td>
<td>1.427997e+19</td>
<td>11.896213</td>
<td>44.10539</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Viet Nam</td>
<td>5816</td>
<td>3.343653e+17</td>
<td>8.668368</td>
<td>40.35101</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>Chile</td>
<td>3952</td>
<td>2.782851e+17</td>
<td>8.281977</td>
<td>40.16742</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Korea, Republic of</td>
<td>8042</td>
<td>1.651423e+18</td>
<td>8.992433</td>
<td>41.94817</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>Japan</td>
<td>515</td>
<td>5.117994e+18</td>
<td>6.244167</td>
<td>43.07929</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Spain</td>
<td>2336</td>
<td>1.403496e+18</td>
<td>7.756195</td>
<td>41.78550</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>United States of America</td>
<td>6629</td>
<td>2.153998e+19</td>
<td>8.799209</td>
<td>44.51644</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Philippines</td>
<td>1254</td>
<td>3.768234e+17</td>
<td>7.134094</td>
<td>40.47055</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>France</td>
<td>3167</td>
<td>2.722794e+18</td>
<td>8.060540</td>
<td>42.44819</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Hong Kong, China</td>
<td>532</td>
<td>3.630745e+17</td>
<td>6.276643</td>
<td>40.43338</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>China</td>
<td>139935</td>
<td>1.468774e+19</td>
<td>11.848933</td>
<td>44.13354</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Viet Nam</td>
<td>5854</td>
<td>3.466157e+17</td>
<td>8.674881</td>
<td>40.38699</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>Chile</td>
<td>3438</td>
<td>2.540422e+17</td>
<td>8.142645</td>
<td>40.07628</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Korea, Republic of</td>
<td>7817</td>
<td>1.644313e+18</td>
<td>8.964056</td>
<td>41.94385</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>Japan</td>
<td>725</td>
<td>5.055587e+18</td>
<td>6.586172</td>
<td>43.06703</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Spain</td>
<td>2127</td>
<td>1.289784e+18</td>
<td>7.662468</td>
<td>41.70101</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>United States of America</td>
<td>3011</td>
<td>2.135411e+19</td>
<td>8.010027</td>
<td>44.50778</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Philippines</td>
<td>655</td>
<td>3.617511e+17</td>
<td>6.484635</td>
<td>40.42973</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>France</td>
<td>3297</td>
<td>2.647926e+18</td>
<td>8.100768</td>
<td>42.42031</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Hong Kong, China</td>
<td>461</td>
<td>3.449431e+17</td>
<td>6.133398</td>
<td>40.38216</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>China</td>
<td>157763</td>
<td>1.782046e+19</td>
<td>11.968849</td>
<td>44.32688</td>
</tr>
<tr class="even">
<td>2021</td>
<td>Viet Nam</td>
<td>8613</td>
<td>3.664748e+17</td>
<td>9.061028</td>
<td>40.44271</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>Chile</td>
<td>2870</td>
<td>3.155150e+17</td>
<td>7.962067</td>
<td>40.29298</td>
</tr>
<tr class="even">
<td>2021</td>
<td>Korea, Republic of</td>
<td>5193</td>
<td>1.818432e+18</td>
<td>8.555067</td>
<td>42.04451</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>Japan</td>
<td>897</td>
<td>5.034621e+18</td>
<td>6.799056</td>
<td>43.06287</td>
</tr>
<tr class="even">
<td>2021</td>
<td>Spain</td>
<td>1975</td>
<td>1.461245e+18</td>
<td>7.588324</td>
<td>41.82582</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>United States of America</td>
<td>4261</td>
<td>2.368117e+19</td>
<td>8.357259</td>
<td>44.61121</td>
</tr>
<tr class="even">
<td>2021</td>
<td>Philippines</td>
<td>1389</td>
<td>3.940874e+17</td>
<td>7.236339</td>
<td>40.51535</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>France</td>
<td>2470</td>
<td>2.966434e+18</td>
<td>7.811973</td>
<td>42.53389</td>
</tr>
<tr class="even">
<td>2021</td>
<td>Hong Kong, China</td>
<td>495</td>
<td>3.689542e+17</td>
<td>6.204558</td>
<td>40.44945</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>China</td>
<td>170002</td>
<td>1.788178e+19</td>
<td>12.043565</td>
<td>44.33031</td>
</tr>
<tr class="even">
<td>2022</td>
<td>Viet Nam</td>
<td>5713</td>
<td>4.103240e+17</td>
<td>8.650500</td>
<td>40.55572</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>Chile</td>
<td>4234</td>
<td>3.021165e+17</td>
<td>8.350903</td>
<td>40.24959</td>
</tr>
<tr class="even">
<td>2022</td>
<td>Korea, Republic of</td>
<td>7818</td>
<td>1.673917e+18</td>
<td>8.964184</td>
<td>41.96170</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>Japan</td>
<td>1173</td>
<td>4.256411e+18</td>
<td>7.067320</td>
<td>42.89496</td>
</tr>
<tr class="even">
<td>2022</td>
<td>Spain</td>
<td>1861</td>
<td>1.446498e+18</td>
<td>7.528869</td>
<td>41.81568</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>United States of America</td>
<td>5297</td>
<td>2.600689e+19</td>
<td>8.574896</td>
<td>44.70489</td>
</tr>
<tr class="even">
<td>2022</td>
<td>Philippines</td>
<td>2449</td>
<td>4.043534e+17</td>
<td>7.803435</td>
<td>40.54107</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>France</td>
<td>5820</td>
<td>2.796302e+18</td>
<td>8.669056</td>
<td>42.47483</td>
</tr>
<tr class="even">
<td>2022</td>
<td>Hong Kong, China</td>
<td>501</td>
<td>3.586811e+17</td>
<td>6.216606</td>
<td>40.42121</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>China</td>
<td>190607</td>
<td>1.779478e+19</td>
<td>12.157969</td>
<td>44.32544</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Viet Nam</td>
<td>9817</td>
<td>4.297170e+17</td>
<td>9.191871</td>
<td>40.60190</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>Chile</td>
<td>4900</td>
<td>3.355333e+17</td>
<td>8.496991</td>
<td>40.35450</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Korea, Republic of</td>
<td>4234</td>
<td>1.712793e+18</td>
<td>8.350903</td>
<td>41.98466</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>Japan</td>
<td>2137</td>
<td>4.204495e+18</td>
<td>7.667158</td>
<td>42.88269</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Spain</td>
<td>2120</td>
<td>1.620091e+18</td>
<td>7.659171</td>
<td>41.92901</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>United States of America</td>
<td>1917</td>
<td>2.772071e+19</td>
<td>7.558517</td>
<td>44.76871</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Philippines</td>
<td>1727</td>
<td>4.371464e+17</td>
<td>7.454141</td>
<td>40.61904</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>France</td>
<td>900</td>
<td>3.051832e+18</td>
<td>6.802395</td>
<td>42.56227</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Hong Kong, China</td>
<td>390</td>
<td>3.808122e+17</td>
<td>5.966147</td>
<td>40.48108</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2019-2023, data yang dipakai ialah data yang telah diolah dengan sumber World Development Indicators, World Bank, dan Trademap.org.</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara Export dan GDP. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah nilai export rumput laut dan <span class="math inline">\(x_t\)</span> adalah GDP negara tujuan.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">'MTPL.xlsx'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Tahun"</span>, <span class="st">"Negara"</span>, <span class="st">"Export"</span>, <span class="st">"GDP"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Export <span class="sc">&gt;</span> <span class="dv">0</span>, GDP <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>lexport <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>Export)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>lpdb <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>GDP)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> lpdb, <span class="at">y =</span> lexport)) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Tabel 1. Hubungan antara Log GDP dan Log Ekspor"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Log Produk Domestic Bruto (GDP)"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Log Nilai Ekspor (Tons)"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Sumber: World Development Indicators, World Bank"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">'MTPL.xlsx'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Tahun"</span>, <span class="st">"Negara"</span>, <span class="st">"Export"</span>, <span class="st">"GDP"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Export <span class="sc">&gt;</span> <span class="dv">0</span>, GDP <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>lexport <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>Export)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>lpdb <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>GDP)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpdb <span class="sc">~</span> lexport, <span class="at">data =</span> dat)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m <span class="ot">&lt;-</span> <span class="fu">resid</span>(reg1)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>lpdb, dat<span class="sc">$</span>m,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Log GDP (USD)"</span>, <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Log GDP terhadap Error"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>! <a href="">Plot pengaruh eror terhadap GDP</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">'MTPL.xlsx'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Tahun"</span>, <span class="st">"Negara"</span>, <span class="st">"Export"</span>, <span class="st">"GDP"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Export <span class="sc">&gt;</span> <span class="dv">0</span>, GDP <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>lexport <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>Export)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>lpdb <span class="ot">&lt;-</span> <span class="fu">log</span>(dat<span class="sc">$</span>GDP)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpdb <span class="sc">~</span> lexport, <span class="at">data =</span> dat)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m <span class="ot">&lt;-</span> <span class="fu">resid</span>(reg1)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>lexport, dat<span class="sc">$</span>m,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Log Export (ton)"</span>, <span class="at">ylab =</span> <span class="st">"Error"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Log Export terhadap Error"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>! <a href="">Plot pengaruh eror terhadap Export</a></p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 20%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Variabel</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-value</th>
<th>Prob (p-value)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-11.1795</td>
<td>5.3988</td>
<td>-2.071</td>
<td>0.0438 (*)</td>
</tr>
<tr class="even">
<td>lpdb (GDP)</td>
<td>0.4614</td>
<td>0.1285</td>
<td>3.590</td>
<td>0.0008 (***)</td>
</tr>
<tr class="odd">
<td><strong>R-squared</strong></td>
<td>0.2117</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Adjusted R-squared</strong></td>
<td>0.1952</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>F-Statistic</strong></td>
<td>12.89</td>
<td></td>
<td></td>
<td>0.0008</td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang telah didapat dimasukan ke dalam rumus persamaan yang ada sehingga menjadi: <span class="math display">\[
y_{t}= -11.1795 + 0.4614 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah Log volume ekspor rumput laut Indonesia (dependent variable) dan <span class="math inline">\(x_t\)</span> adalah Log GDP negara tujuan ekspor utama (independent variable).</p>
<section id="interpretasi-hasil" class="level4" data-number="4.1.1">
<h4 data-number="4.1.1" class="anchored" data-anchor-id="interpretasi-hasil"><span class="header-section-number">4.1.1</span> Interpretasi Hasil</h4>
<ol type="1">
<li><p>Koefisien Intercept: Nilai intercept sebesar -11.1795 menunjukkan nilai log volume ekspor rumput laut ketika GDP negara tujuan (log GDP) bernilai nol. Intercept ini memiliki p-value sebesar 0.0438, yang menunjukkan signifikan pada tingkat kepercayaan 5%.</p></li>
<li><p>Koefisien lpdb (GDP): Nilai koefisien GDP sebesar 0.4614 mengindikasikan bahwa setiap peningkatan 1% pada log GDP negara tujuan akan meningkatkan log volume ekspor rumput laut Indonesia sebesar 0.4614%. Koefisien ini signifikan pada tingkat kepercayaan 1% (p-value = 0.0008).</p></li>
<li><p>R-squared dan Adjusted R-squared: R-squared sebesar 0.2117 berarti model ini menjelaskan sekitar 21.17% variasi dalam log volume ekspor rumput laut berdasarkan log GDP negara tujuan. Adjusted R-squared sebesar 0.1952 menunjukkan bahwa setelah memperhitungkan jumlah variabel independen, model ini menjelaskan 19.52% variasi dalam data.</p></li>
<li><p>F-Statistic: Nilai F-statistic sebesar 12.89 dengan p-value 0.0008 menunjukkan bahwa model ini secara keseluruhan signifikan, sehingga GDP negara tujuan secara statistik berpengaruh terhadap log volume ekspor rumput laut Indonesia.</p></li>
</ol>
<p>Ekspor memiliki peran dalam pertumbuhan ekonomi negara tujuan, khususnya untuk meningkatkan volume ekspor rumput laut Indonesia. Hal ini ditunjukkan oleh koefisien GDP yang positif dan signifikan. Namun, nilai R-squared yang relatif rendah menunjukkan bahwa variabel independen lain juga berpengaruh terhadap volume ekspor, yang tidak dijelaskan dalam model ini.</p>
</section>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lexport <span class="sc">~</span> lpdb, <span class="at">data =</span> dat)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lexport ~ lpdb, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4525 -1.0321 -0.3177  0.9045  2.8863 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -11.1795     5.3988  -2.071 0.043785 *  
lpdb          0.4614     0.1285   3.590 0.000775 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.39 on 48 degrees of freedom
Multiple R-squared:  0.2117,    Adjusted R-squared:  0.1952 
F-statistic: 12.89 on 1 and 48 DF,  p-value: 0.0007753</code></pre>
</div>
</div>
<p>Jika diasumsikan GDP meningkat 1 unit logaritmik, maka volume ekspor logaritmik akan meningkat sebesar 0.4614 unit logaritmik. Namun, faktor lain di luar GDP juga perlu dipertimbangkan untuk meningkatkan ekspor rumput laut Indonesia.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukan penelitian melalui metode regresi linier, maka dapat disimpulkan beberapa hal sebagai berikut:</p>
<ol type="1">
<li><p>Pengaruh GDP terhadap Volume Ekspor Rumput Laut GDP negara tujuan ekspor memiliki pengaruh positif terhadap volume ekspor rumput laut Indonesia ke 10 negara utama selama tahun 2019-2023. Hal ini sesuai dengan teori perdagangan internasional yang menyatakan bahwa semakin tinggi tingkat ekonomi (GDP) suatu negara, maka daya beli dan permintaan terhadap produk impor, termasuk rumput laut, akan meningkat.</p></li>
<li><p>Signifikansi Hubungan Berdasarkan hasil regresi, GDP secara signifikan memengaruhi volume ekspor dengan nilai koefisien sebesar 0.4614 dan tingkat signifikansi 𝑝&lt;0.001 p&lt;0.001. Ini menunjukkan bahwa setiap peningkatan 1% dalam GDP negara tujuan akan meningkatkan volume ekspor rumput laut sebesar 0.4614%, dengan asumsi variabel lain tetap.</p></li>
<li><p>Keterbatasan Model Meskipun GDP memiliki pengaruh positif yang signifikan, nilai sebesar 0.2117 menunjukkan bahwa hanya sekitar 21.17% variasi dalam volume ekspor yang dapat dijelaskan oleh GDP. Hal ini menunjukkan bahwa volume ekspor rumput laut juga dipengaruhi oleh faktor lain yang tidak dimasukkan dalam model, seperti kebijakan perdagangan, nilai tukar, infrastruktur logistik, atau harga komoditas di pasar global.</p></li>
<li><p>Implikasi dan Saran Untuk meningkatkan volume ekspor rumput laut, Indonesia perlu memperhatikan faktor-faktor lain di luar GDP negara tujuan. Kebijakan yang mendukung efisiensi logistik, diversifikasi pasar, serta promosi dagang ke negara-negara dengan pertumbuhan GDP tinggi dapat menjadi strategi yang efektif.</p></li>
<li><p>Keseimbangan Ekspor dan Faktor Pendukung Dalam perdagangan internasional, ekspor memiliki peran penting dalam menghasilkan arus modal masuk. Namun, keberlanjutan ekspor tidak hanya bergantung pada permintaan dari negara tujuan, tetapi juga pada kemampuan dalam negeri untuk meningkatkan kapasitas produksi dan menjaga kualitas produk.</p></li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Arthatiani, F., Wardono, B., Luhur, E., &amp; Apriliani, T. (2021). ANALISIS SITUASIONAL KINERJA EKSPOR RUMPUT LAUT INDONESIA PADA MASA PANDEMI COVID-19. Jurnal Kebijakan Sosial Ekonomi Kelautan Dan Perikanan, 11, 1. https://doi.org/10.15578/jksekp.v11i1.9501</p>
<p>Atillah, R., &amp; Gischa, S. (2023). Rumput Laut: Pengertian, Pemanfaatan dan Jenisnya. Kompas.Com. https://www.kompas.com/skola/read/2023/11/18/020000869/rumput-laut–pengertian-pemanfaatan-dan-jenisnya-#google_vignette</p>
<p>Gravitty model and Time Series. (n.d.). Retrieved January 1, 2025, from https://www.krisna.or.id/metopel/meeting5/#/gravity-data</p>
<p>Salim, Z. (Ed.). (2015). Info komoditi Rumput Laut. Badan Pengkajian dan Pengembangan Kebijakan Perdagangan : Al Mawardi Prima.</p>
<p>Saputra, E. A. N. P. (2024). ANALISIS FAKTOR-FAKTOR YANG MEMPENGARUHI VOLUME EKSPOR RUMPUT LAUT INDONESIA KE 10 NEGARA TUJUAN UTAMA TAHUN 2018-2022 [Masters, Wijaya Kusuma Surabaya University]. https://doi.org/10/ARTIKEL.pdf</p>
<p>Simanjuntak, P. T. H., Arifin, Z., &amp; Mawardi, M. K. (n.d.). PENGARUH PRODUKSI, HARGA INTERNASIONAL DAN NILAI TUKAR RUPIAH TERHADAP VOLUME EKSPOR RUMPUT LAUT INDONESIA. 50(3).</p>
<p>Referensi ini dibuat dengan Zotero.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>